### ISSUE TITLE
Exception is thrown when clicked on empty Output sidebar

### ISSUE THREAD

**Issue by Saffie** [adamIqbal/Health#133]

**Comment by mvandorp** [comment]
Hey,
We've got some great news for you! Just take a look  http://offer.skylineartcrawl.com/e2incss

All best, martijnvandorp@casema.nl

**Comment by mvandorp** [comment]
Hi friend! 

I know you're interested  in stuff like that, that is something  really cool, just take a look http://positive.alisssandra.com/e5tjvlm

martijnvandorp

93835067

**Comment by mvandorp** [comment]
Greetings! 

I've  found a  very easy tutorial on the stuff  we were talking about, look here http://prior.cravingshut.com/e5hyzh

Warmest, martijnvandorp

2910217

**Comment by mvandorp** [comment]
Hi! 

I've just found that arcticle and  thought it might be  really helpful to you, you may find it here http://chongunkyphu.plbudget.com/e5ttmg

Thanks for your consideration, martijnvandorp

**Comment by mvandorp** [comment]
Dear, 

Here  is some information that inspired me a lot, read it please, it may be helpful  http://thezytrandy.quantumcreating.com/e2oge

My best to you, martijnvandorp
