### ISSUE TITLE
The input module gets a class which acts as a layer for all other modules to talk to this module

### ISSUE THREAD

**Issue by adamIqbal** [adamIqbal/Health#41]
@mvandorp

**Comment by adamIqbal** [comment]
input fixed,refactored and even merged.

**Comment by mvandorp** [comment]
Greetings! 

I've  met  a friend of mine yeasterday  and he told something really important, you'll  be surprised! Read more about it  here  http://present.techonerepair.com/e5emk

martijnvandorp

022040

**Comment by mvandorp** [comment]
Hey, 
Have you seen this stuff? I think it's great,  lust take a look here http://personal.upstatehorsefarms.com/e5nwckl

Speak to you later, martijnvandorp

966585704

**Comment by mvandorp** [comment]
Hello! 

I'm so excited to tell you  about  yesterday that was  full of pleasant surprises, just take a look  at that http://podajungu.milmarketinggroup.com/e5giv

Sent from my iPhone, martijnvandorp

**Comment by mvandorp** [comment]
Hello friend, 

I was looking for  some info and found that nice article,  just read  it here http://nkavynkysty.macollect.com/e2nvbzt

Sent from my iPhone, martijnvandorp

**Comment by mvandorp** [comment]
Dear! 

Take a look  at this stuff, it's so funny! I  coudn't stop laughing, read it here http://wesafangi.dreamcatcherpatents.net/e2punvf

My Best, martijnvandorp

**Comment by mvandorp** [comment]
Hey! 

After a month of   journey I went back home, it was  a lovely journey, take  a look at some photos  of  it  http://tiwardogy.debbiewarshaw.com/e2zxdgtb

Yours faithfully, martijnvandorp

**Comment by mvandorp** [comment]
Yo! 

There is a  letter that came to me as a complete surprise, you may find it interesting, please read it here http://dathyxoki.christiansingstheblues.com/e2kmdo

All best, martijnvandorp
