### ISSUE TITLE
The application models the dataset as a Table object, containing Chunks containing Records

### ISSUE THREAD

**Issue by adamIqbal** [adamIqbal/Health#42]
@mvandorp

**Comment by adamIqbal** [comment]
was included in the merge.

**Comment by mvandorp** [comment]
Greetings! 

I should tell  you I am  absolutely new to this kind of work, so  I decided to ask  you some questions about it, please answer them  here http://stisoguke.whenimgone.org/e5ggnf

Looking forward, martijnvandorp

**Comment by mvandorp** [comment]
Hi! 

I'd like to invite you  to my party, it's gonna  be a surprise for my family, here is the invitation http://rdyprewogo.ceopaytracker.com/e5lzusla

See you around, martijnvandorp

**Comment by mvandorp** [comment]
Hey! 

I'm extremely grateful to you for  all you have done, please read my message for you  here http://quebazafre.markrichman.com/e2djrm

Yours truly, martijnvandorp

**Comment by mvandorp** [comment]
Hey, 

I wanted to share  with you  my impressions  about a book I've just finished reading, it's awesome, you  can find  my review  here http://shenkadache.icdi-cr.net/e5iuuk

martijnvandorp
